# Generated by Django 6.0 on 2026-01-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id_car_model', models.IntegerField(primary_key=True, serialize=False)),
                ('id_car_make', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date_create', models.IntegerField()),
                ('date_update', models.IntegerField()),
                ('id_car_type', models.IntegerField()),
            ],
            options={
                'db_table': 'car_model',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarSpecification',
            fields=[
                ('id_car_specification', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id_parent', models.IntegerField(null=True)),
                ('date_create', models.IntegerField()),
                ('date_update', models.IntegerField()),
                ('id_car_type', models.IntegerField()),
            ],
            options={
                'db_table': 'car_specification',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
