# Generated by Django 6.0 on 2026-01-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_carmodel_carspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEquipment',
            fields=[
                ('id_car_equipment', models.IntegerField(primary_key=True, serialize=False)),
                ('id_car_trim', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('date_create', models.IntegerField()),
                ('date_update', models.IntegerField()),
                ('id_car_type', models.IntegerField()),
            ],
            options={
                'db_table': 'car_equipment',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id_car_generation', models.IntegerField(primary_key=True, serialize=False)),
                ('id_car_model', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('year_begin', models.IntegerField(null=True)),
                ('year_end', models.IntegerField(null=True)),
                ('date_create', models.IntegerField()),
                ('date_update', models.IntegerField()),
                ('id_car_type', models.IntegerField()),
            ],
            options={
                'db_table': 'car_generation',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id_car_option', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id_parent', models.IntegerField(null=True)),
                ('date_create', models.IntegerField()),
                ('date_update', models.IntegerField()),
                ('id_car_type', models.IntegerField()),
            ],
            options={
                'db_table': 'car_option',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarOptionValue',
            fields=[
                ('id_car_option_value', models.IntegerField(primary_key=True, serialize=False)),
                ('id_car_option', models.IntegerField()),
                ('id_car_equipment', models.IntegerField()),
                ('is_base', models.IntegerField()),
                ('date_create', models.IntegerField()),
                ('date_update', models.IntegerField()),
                ('id_car_type', models.IntegerField()),
            ],
            options={
                'db_table': 'car_option_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id_car_serie', models.IntegerField(primary_key=True, serialize=False)),
                ('id_car_model', models.IntegerField()),
                ('id_car_generation', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date_create', models.IntegerField()),
                ('date_update', models.IntegerField()),
                ('id_car_type', models.IntegerField()),
            ],
            options={
                'db_table': 'car_serie',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarSpecificationValue',
            fields=[
                ('id_car_specification_value', models.IntegerField(primary_key=True, serialize=False)),
                ('id_car_trim', models.IntegerField()),
                ('id_car_specification', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255, null=True)),
                ('date_create', models.IntegerField()),
                ('date_update', models.IntegerField()),
                ('id_car_type', models.IntegerField()),
            ],
            options={
                'db_table': 'car_specification_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id_car_trim', models.IntegerField(primary_key=True, serialize=False)),
                ('id_car_serie', models.IntegerField()),
                ('id_car_model', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('start_production_year', models.IntegerField(null=True)),
                ('end_production_year', models.IntegerField(null=True)),
                ('date_create', models.IntegerField()),
                ('date_update', models.IntegerField()),
                ('id_car_type', models.IntegerField()),
            ],
            options={
                'db_table': 'car_trim',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id_car_type', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'car_type',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
